mysql:
  1:
    dbname: poker
    user: root
    password: 123456
    host: localhost:13306
    slave:

redis:
  1:
    dbname: poker
    db: 1
    user: default
    password: 123456
    host: localhost:16379

mongodb:
  1:
    dbname: poker
    user: root
    password: 123456
    host: localhost:17017
    slave:
      1:
        dbname: poker
        user: root
        password: 123456
        host: localhost:17017

etcd:
  topic: poker_server/etcd
  endpoints:
    - http://localhost:12379

nats:
  topic: poker_server/nats
  endpoints: localhost:14222

common:
  env: develop  # develop, beta, release 
  config_is_remote: true
  config_path: ./data
  config_topic: poker/config
  router_expire: 90000
  discovery_expire: 20
  secret_key: gH7%kL9!qW2#sD4*FpV6&nZ8@xJ0^yT1

php:
  user_info_url: http://192.168.50.250:8000/mg/callback/ACE/getUserInfo

client:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/client.log
    ip: localhost
    port: 10101
    http_port: 22345

gate:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/gate1.log
    ip: localhost
    port: 10101
    http_port: 10001

room:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/room1.log
    ip: localhost
    port: 10201

match:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/match1.log
    ip: localhost
    port: 10301


db:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/db1.log
    ip: localhost
    port: 10401

builder:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/builder1.log
    ip: localhost
    port: 10501

game:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/game1.log
    ip: localhost
    port: 10601

gm:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/gm1.log
    ip: localhost
    port: 10701