services:
  mysql:
    image: mysql:8.4.3
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: universal
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      universal_network:

  redis:
    image: redis:7.4.0
    restart: always
    container_name: redis
    environment:
      REDIS_USER: root
      REDIS_PASSWORD: 123456
    ports:
      - "6379:6379"
    networks:
      universal_network:


  mongodb:
    image: mongo:6.0
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: universal
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    networks:
      universal_network:

  etcd:
    image: bitnami/etcd:3.5
    restart: always
    container_name: etcd
    environment:
      # 允许无认证访问（生产环境不建议）
      - ALLOW_NONE_AUTHENTICATION=yes  
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "33601:2379"
      - "33602:2380"
    networks:
      universal_network:

  zookeeper:
    image: ubuntu/zookeeper
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      universal_network:

  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    restart: always
    container_name: rabbitmq
    hostname: bt-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_LOOPBACK_USERS: "none" # 允许 guest 远程访问
    ports:
      - "5672:5672" # 映射 RabbitMQ 的 AMQP 端口
      - "15672:15672" # 映射 RabbitMQ 的管理界面端口
    networks:
      universal_network:

  consul:
    image: hashicorp/consul:1.12.3
    restart: always
    container_name: consul
    ports:
      - "8500:8500"  # HTTP API 和 UI 端口
      - "8600:8600/udp"  # DNS 端口
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=true
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    networks:
      universal_network:
  

  nats:
    image: nats:2.9-alpine
    container_name: nats
    ports:
      - "4222:4222"  # 客户端端口
      - "8222:8222"  # 监控端口
    command: >
      --cluster nats://0.0.0.0:6222
      --routes nats://nats2:6222,nats://nats3:6222
      --cluster_name NATS_CLUSTER
      --debug
      --trace
    networks:
      universal_network:

  # NSQ 服务发现组件
  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    container_name: nsqlookupd
    command: /nsqlookupd
    ports:
      - "4160:4160"  # TCP 端口，供 nsqd 注册
      - "4161:4161"  # HTTP 端口，供客户端查询
    networks:
      universal_network:
    
  nsqd:
    image: nsqio/nsq:v1.2.1
    container_name: nsqd
    depends_on:
      - nsqlookupd
    command: >
      /nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --broadcast-address=192.168.3.5
      --tcp-address=0.0.0.0:4150
      --http-address=0.0.0.0:4151
    ports:
      - "4150:4150"  # 生产者/消费者连接端口
      - "4151:4151"  # HTTP 管理端口
    networks:
      universal_network:
  
  nsqadmin:
    image: nsqio/nsq:v1.2.1
    container_name: nsqadmin
    depends_on:
      - nsqlookupd
      - nsqd
    command: >
      /nsqadmin
      --lookupd-http-address=nsqlookupd:4161
      --http-address=0.0.0.0:4171
    ports:
      - "4171:4171"  # 管理界面端口    
    networks:
      universal_network:

networks:
  universal_network:
    driver: bridge
