mysql:
  1:
    dbname: poker
    user: root
    password: 123456
    host: 192.168.50.250:13306
    slave:

redis:
  1:
    dbname: poker
    db: 1
    user: default
    password: 123456
    host: 192.168.50.250:16379
  
mongodb:
  1:
    dbname: poker
    user: root
    password: 123456
    host: 192.168.50.250:17017
    slave: 
      1: 
        dbname: poker
        user: root
        password: 123456
        host: 192.168.50.250:17017
    
etcd:
  topic: poker_server/etcd
  endpoints:
    - http://192.168.50.250:12379


nats:
  topic: poker_server/nats
  endpoints: 192.168.50.250:14222

common:
  env: develop  # develop, beta, release 
  config_is_remote: true
  config_path: D:/project/src/poker_gameconf/output
  config_topic: poker/config
  router_expire: 900
  discovery_expire: 20
  secret_key: gH7%kL9!qW2#sD4*FpV6&nZ8@xJ0^yT1

php:
  user_info_url: http://192.168.50.250:8000/mg/callback/ACE/getUserInfo

client:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: winfile:///D:/project/src/poker_server/output/log/client.log
    ip: 192.168.50.250
    http_port: 22345
    port: 10101
  
gate:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: winfile:///D:/project/src/poker_server/output/log/gate.log
    ip: 192.168.50.250
    http_port: 10001
    port: 10101

room:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: winfile:///D:/project/src/poker_server/output/log/room.log
    ip: 192.168.50.250
    port: 10201
  
match:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: winfile:///D:/project/src/poker_server/output/log/match.log
    ip: 192.168.50.250
    port: 10301

db:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: winfile:///D:/project/src/poker_server/output/log/db.log
    ip: 192.168.50.250
    port: 10401

builder:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: winfile:///D:/project/src/poker_server/output/log/builder.log
    ip: 192.168.50.250
    port: 10501

game:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: winfile:///D:/project/src/poker_server/output/log/game.log
    ip: 192.168.50.250
    port: 10601

gm:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: winfile:///D:/project/src/poker_server/output/log/gm.log
    ip: 192.168.50.250
    port: 10701


