mysql:
  1:
    dbname: poker
    user: root
    password: 123456
    host: localhost:3306
    slave:

redis:
  1:
    dbname: poker
    db: 1
    user: default
    password: 123456
    host: localhost:6379
  
mongodb:
  1:
    dbname: poker
    user: root
    password: 123456
    host: localhost:27017
    slave: #从设备
      1: localhost:27017
      2: localhost:27017
    
etcd:
  channel: poker_server/etcd
  endpoints:
    - http://localhost:33601
    - http://localhost:33611
    - http://localhost:33621

nats:
  channel: poker_server/nats
  endpoints: localhost:4222

configure:
  local_path: ../../../poker_gameconf/json

cluster:
  gate:
    env: develop  # develop, beta, release 
    log_level: debug # info, debug, warn, error, fatal
    log_path: ../../output/gate.log
    router_expire: 5
    discovery_expire: 20
    nodes:
      1: :40001


