// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.2
// source: enum.gen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举配置表1
type ROUTE int32

const (
	ROUTE_UID      ROUTE = 0 // 路由类型-玩家ID
	ROUTE_RegionID ROUTE = 1 // 路由类型-区服ID
)

// Enum value maps for ROUTE.
var (
	ROUTE_name = map[int32]string{
		0: "UID",
		1: "RegionID",
	}
	ROUTE_value = map[string]int32{
		"UID":      0,
		"RegionID": 1,
	}
)

func (x ROUTE) Enum() *ROUTE {
	p := new(ROUTE)
	*p = x
	return p
}

func (x ROUTE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ROUTE) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[0].Descriptor()
}

func (ROUTE) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[0]
}

func (x ROUTE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ROUTE.Descriptor instead.
func (ROUTE) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{0}
}

// 枚举配置表2
type SEND int32

const (
	SEND_Point     SEND = 0 // 发送类型-点对点
	SEND_Broadcast SEND = 1 // 发送类型-广播
)

// Enum value maps for SEND.
var (
	SEND_name = map[int32]string{
		0: "Point",
		1: "Broadcast",
	}
	SEND_value = map[string]int32{
		"Point":     0,
		"Broadcast": 1,
	}
)

func (x SEND) Enum() *SEND {
	p := new(SEND)
	*p = x
	return p
}

func (x SEND) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SEND) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[1].Descriptor()
}

func (SEND) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[1]
}

func (x SEND) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SEND.Descriptor instead.
func (SEND) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{1}
}

// 枚举配置表2
type SERVER int32

const (
	SERVER_Gate SERVER = 0 // 服务器类型-Gate
	SERVER_Game SERVER = 1 // 服务器类型-Game
	SERVER_Db   SERVER = 2 // 服务器类型-Db
	SERVER_Gm   SERVER = 3 // 服务器类型-Gm
)

// Enum value maps for SERVER.
var (
	SERVER_name = map[int32]string{
		0: "Gate",
		1: "Game",
		2: "Db",
		3: "Gm",
	}
	SERVER_value = map[string]int32{
		"Gate": 0,
		"Game": 1,
		"Db":   2,
		"Gm":   3,
	}
)

func (x SERVER) Enum() *SERVER {
	p := new(SERVER)
	*p = x
	return p
}

func (x SERVER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SERVER) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[2].Descriptor()
}

func (SERVER) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[2]
}

func (x SERVER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SERVER.Descriptor instead.
func (SERVER) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{2}
}

var File_enum_gen_proto protoreflect.FileDescriptor

var file_enum_gen_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x2a, 0x1e, 0x0a, 0x05, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x12, 0x07, 0x0a,
	0x03, 0x55, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x10, 0x01, 0x2a, 0x20, 0x0a, 0x04, 0x53, 0x45, 0x4e, 0x44, 0x12, 0x09, 0x0a, 0x05,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x10, 0x01, 0x2a, 0x2c, 0x0a, 0x06, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52,
	0x12, 0x08, 0x0a, 0x04, 0x47, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x61,
	0x6d, 0x65, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x44, 0x62, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02,
	0x47, 0x6d, 0x10, 0x03, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_gen_proto_rawDescOnce sync.Once
	file_enum_gen_proto_rawDescData = file_enum_gen_proto_rawDesc
)

func file_enum_gen_proto_rawDescGZIP() []byte {
	file_enum_gen_proto_rawDescOnce.Do(func() {
		file_enum_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_gen_proto_rawDescData)
	})
	return file_enum_gen_proto_rawDescData
}

var file_enum_gen_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_enum_gen_proto_goTypes = []interface{}{
	(ROUTE)(0),  // 0: pb.ROUTE
	(SEND)(0),   // 1: pb.SEND
	(SERVER)(0), // 2: pb.SERVER
}
var file_enum_gen_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_gen_proto_init() }
func file_enum_gen_proto_init() {
	if File_enum_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_gen_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_gen_proto_goTypes,
		DependencyIndexes: file_enum_gen_proto_depIdxs,
		EnumInfos:         file_enum_gen_proto_enumTypes,
	}.Build()
	File_enum_gen_proto = out.File
	file_enum_gen_proto_rawDesc = nil
	file_enum_gen_proto_goTypes = nil
	file_enum_gen_proto_depIdxs = nil
}
