//
// 本代码由cfgtool工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.0
// source: global_enum_cfg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_NodeTypeBegin   NodeType = 0 // 节点类型-begin
	NodeType_NodeTypeGate    NodeType = 1 // 节点类型-Gate
	NodeType_NodeTypeMatch   NodeType = 2 // 节点类型-Match
	NodeType_NodeTypeRoom    NodeType = 3 // 节点类型-Room
	NodeType_NodeTypeDb      NodeType = 4 // 节点类型-Db
	NodeType_NodeTypeBuilder NodeType = 5 // 节点类型-Builder
	NodeType_NodeTypeGm      NodeType = 6 // 节点类型-Gm
	NodeType_NodeTypeGame    NodeType = 7 // 节点类型-Game
	NodeType_NodeTypeEnd     NodeType = 8 // 节点类型-End
	NodeType_NodeTypeClient  NodeType = 9 // 节点类型-Client
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NodeTypeBegin",
		1: "NodeTypeGate",
		2: "NodeTypeMatch",
		3: "NodeTypeRoom",
		4: "NodeTypeDb",
		5: "NodeTypeBuilder",
		6: "NodeTypeGm",
		7: "NodeTypeGame",
		8: "NodeTypeEnd",
		9: "NodeTypeClient",
	}
	NodeType_value = map[string]int32{
		"NodeTypeBegin":   0,
		"NodeTypeGate":    1,
		"NodeTypeMatch":   2,
		"NodeTypeRoom":    3,
		"NodeTypeDb":      4,
		"NodeTypeBuilder": 5,
		"NodeTypeGm":      6,
		"NodeTypeGame":    7,
		"NodeTypeEnd":     8,
		"NodeTypeClient":  9,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_global_enum_cfg_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_global_enum_cfg_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_global_enum_cfg_proto_rawDescGZIP(), []int{0}
}

var File_global_enum_cfg_proto protoreflect.FileDescriptor

var file_global_enum_cfg_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x66,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x6c, 0x2a, 0xc0, 0x01, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x11, 0x0a, 0x0d, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x61,
	0x74, 0x65, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x64,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x62, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x6f, 0x64,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x10, 0x05, 0x12, 0x0e,
	0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x6d, 0x10, 0x06, 0x12, 0x10,
	0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x07,
	0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x64, 0x10,
	0x08, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x10, 0x09, 0x42, 0x15, 0x5a, 0x13, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_global_enum_cfg_proto_rawDescOnce sync.Once
	file_global_enum_cfg_proto_rawDescData = file_global_enum_cfg_proto_rawDesc
)

func file_global_enum_cfg_proto_rawDescGZIP() []byte {
	file_global_enum_cfg_proto_rawDescOnce.Do(func() {
		file_global_enum_cfg_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_enum_cfg_proto_rawDescData)
	})
	return file_global_enum_cfg_proto_rawDescData
}

var file_global_enum_cfg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_global_enum_cfg_proto_goTypes = []interface{}{
	(NodeType)(0), // 0: universal.NodeType
}
var file_global_enum_cfg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_global_enum_cfg_proto_init() }
func file_global_enum_cfg_proto_init() {
	if File_global_enum_cfg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_enum_cfg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_enum_cfg_proto_goTypes,
		DependencyIndexes: file_global_enum_cfg_proto_depIdxs,
		EnumInfos:         file_global_enum_cfg_proto_enumTypes,
	}.Build()
	File_global_enum_cfg_proto = out.File
	file_global_enum_cfg_proto_rawDesc = nil
	file_global_enum_cfg_proto_goTypes = nil
	file_global_enum_cfg_proto_depIdxs = nil
}
