//
// 本代码由cfgtool工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.0
// source: table_cfg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd        uint32     `protobuf:"varint,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`                                         // 消息唯一ID（一定是偶数）
	ServerType ServerType `protobuf:"varint,2,opt,name=ServerType,proto3,enum=universal.ServerType" json:"ServerType,omitempty"` // 服务类型
	ActorName  string     `protobuf:"bytes,3,opt,name=ActorName,proto3" json:"ActorName,omitempty"`                              // Actor名称
	FuncName   string     `protobuf:"bytes,4,opt,name=FuncName,proto3" json:"FuncName,omitempty"`                                // 请求方法名称
	Request    string     `protobuf:"bytes,5,opt,name=Request,proto3" json:"Request,omitempty"`                                  // 请求协议名
	Response   string     `protobuf:"bytes,6,opt,name=Response,proto3" json:"Response,omitempty"`                                // 应答协议名
}

func (x *RouteConfig) Reset() {
	*x = RouteConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_cfg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfig) ProtoMessage() {}

func (x *RouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_cfg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfig.ProtoReflect.Descriptor instead.
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return file_table_cfg_proto_rawDescGZIP(), []int{0}
}

func (x *RouteConfig) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *RouteConfig) GetServerType() ServerType {
	if x != nil {
		return x.ServerType
	}
	return ServerType_STBegin
}

func (x *RouteConfig) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RouteConfig) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *RouteConfig) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *RouteConfig) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RouteConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*RouteConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *RouteConfigAry) Reset() {
	*x = RouteConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_cfg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfigAry) ProtoMessage() {}

func (x *RouteConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_cfg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfigAry.ProtoReflect.Descriptor instead.
func (*RouteConfigAry) Descriptor() ([]byte, []int) {
	return file_table_cfg_proto_rawDescGZIP(), []int{1}
}

func (x *RouteConfigAry) GetAry() []*RouteConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_table_cfg_proto protoreflect.FileDescriptor

var file_table_cfg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x66, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x1a, 0x0e, 0x65, 0x6e,
	0x75, 0x6d, 0x5f, 0x63, 0x66, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x01, 0x0a,
	0x0b, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x43, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x35,
	0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3a, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x03, 0x41, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x41, 0x72,
	0x79, 0x42, 0x15, 0x5a, 0x13, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_table_cfg_proto_rawDescOnce sync.Once
	file_table_cfg_proto_rawDescData = file_table_cfg_proto_rawDesc
)

func file_table_cfg_proto_rawDescGZIP() []byte {
	file_table_cfg_proto_rawDescOnce.Do(func() {
		file_table_cfg_proto_rawDescData = protoimpl.X.CompressGZIP(file_table_cfg_proto_rawDescData)
	})
	return file_table_cfg_proto_rawDescData
}

var file_table_cfg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_table_cfg_proto_goTypes = []interface{}{
	(*RouteConfig)(nil),    // 0: universal.RouteConfig
	(*RouteConfigAry)(nil), // 1: universal.RouteConfigAry
	(ServerType)(0),        // 2: universal.ServerType
}
var file_table_cfg_proto_depIdxs = []int32{
	2, // 0: universal.RouteConfig.ServerType:type_name -> universal.ServerType
	0, // 1: universal.RouteConfigAry.Ary:type_name -> universal.RouteConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_table_cfg_proto_init() }
func file_table_cfg_proto_init() {
	if File_table_cfg_proto != nil {
		return
	}
	file_enum_cfg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_table_cfg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_cfg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_table_cfg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_table_cfg_proto_goTypes,
		DependencyIndexes: file_table_cfg_proto_depIdxs,
		MessageInfos:      file_table_cfg_proto_msgTypes,
	}.Build()
	File_table_cfg_proto = out.File
	file_table_cfg_proto_rawDesc = nil
	file_table_cfg_proto_goTypes = nil
	file_table_cfg_proto_depIdxs = nil
}
