mysql:
  1:
    dbname: universal
    user: root
    password: 123456
    host: localhost:13306
    slave:

redis:
  1:
    prefix: "develop"
    db: 0
    user: default
    password: 123456
    host: localhost:6379
  
etcd:
  topic: universal/etcd
  endpoints:
    - http://localhost:12379
  
nats:
  topic: universal/nats
  endpoints: localhost:14222

table:
  is_remote: true
  patch: ./data
  topic: universal/table
  endpoints:
    - http://localhost:12379


common:
  env: develop  # develop, beta, release 
  discovery_expire: 20
  secret_key: gH7%kL9!qW2#sD4*FpV6&nZ8@xJ0^yT1

client:
  1:
    router_ttl: 900
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/client.log
    ip: localhost
    port: 10101
    http_port: 22345

gate:
  1:
    router_ttl: 900
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/gate1.log
    ip: localhost
    port: 10101
    http_port: 10001

room:
  1:
    router_ttl: 900
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/room1.log
    ip: localhost
    port: 10201

match:
  1:
    router_ttl: 900
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/match1.log
    ip: localhost
    port: 10301


db:
  1:
    router_ttl: 900
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/db1.log
    ip: localhost
    port: 10401

builder:
  1:
    router_ttl: 900
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/builder1.log
    ip: localhost
    port: 10501
  
game:
  1:
    router_ttl: 900
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/game1.log
    ip: localhost
    port: 10601

gm:
  1:
    router_ttl: 900
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/gm1.log
    ip: localhost
    port: 10701
