// Code generated by protoc-gen-go-xorm. DO NOT EDIT.
// Source: packet.proto

package pb

import (
	"github.com/golang/protobuf/proto"
)

func (x *Node) SetName(val string) {
	x.Name = val
}

func (x *Node) SetAddr(val string) {
	x.Addr = val
}

func (x *Node) SetType(val NodeType) {
	x.Type = val
}

func (x *Node) SetId(val int32) {
	x.Id = val
}

func (x *Node) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *Node) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *Router) SetGate(val int32) {
	x.Gate = val
}

func (x *Router) SetRoom(val int32) {
	x.Room = val
}

func (x *Router) SetMatch(val int32) {
	x.Match = val
}

func (x *Router) SetDb(val int32) {
	x.Db = val
}

func (x *Router) SetBuilder(val int32) {
	x.Builder = val
}

func (x *Router) SetGm(val int32) {
	x.Gm = val
}

func (x *Router) SetGame(val int32) {
	x.Game = val
}

func (x *Router) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *Router) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *NodeRouter) SetNodeType(val NodeType) {
	x.NodeType = val
}

func (x *NodeRouter) SetNodeId(val int32) {
	x.NodeId = val
}

func (x *NodeRouter) SetActorName(val string) {
	x.ActorName = val
}

func (x *NodeRouter) SetFuncName(val string) {
	x.FuncName = val
}

func (x *NodeRouter) SetActorId(val uint64) {
	x.ActorId = val
}

func (x *NodeRouter) SetRouterType(val RouterType) {
	x.RouterType = val
}

func (x *NodeRouter) SetRouter(val *Router) {
	x.Router = val
}

func (x *NodeRouter) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *NodeRouter) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *Head) SetSendType(val SendType) {
	x.SendType = val
}

func (x *Head) SetSrc(val *NodeRouter) {
	x.Src = val
}

func (x *Head) SetDst(val *NodeRouter) {
	x.Dst = val
}

func (x *Head) SetActorName(val string) {
	x.ActorName = val
}

func (x *Head) SetFuncName(val string) {
	x.FuncName = val
}

func (x *Head) SetActorId(val uint64) {
	x.ActorId = val
}

func (x *Head) SetUid(val uint64) {
	x.Uid = val
}

func (x *Head) SetSeq(val uint32) {
	x.Seq = val
}

func (x *Head) SetCmd(val uint32) {
	x.Cmd = val
}

func (x *Head) SetReply(val string) {
	x.Reply = val
}

func (x *Head) SetReference(val int32) {
	x.Reference = val
}

func (x *Head) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *Head) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *Packet) SetHead(val *Head) {
	x.Head = val
}

func (x *Packet) SetBody(val []byte) {
	x.Body = val
}

func (x *Packet) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *Packet) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *RspHead) SetCode(val int32) {
	x.Code = val
}

func (x *RspHead) SetMsg(val string) {
	x.Msg = val
}

func (x *RspHead) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *RspHead) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *Reward) SetPropId(val uint32) {
	x.PropId = val
}

func (x *Reward) SetIncr(val int64) {
	x.Incr = val
}

func (x *Reward) SetTotal(val int64) {
	x.Total = val
}

func (x *Reward) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *Reward) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}
