// Code generated by protoc-gen-go-xorm. DO NOT EDIT.
// Source: player_data.proto

package pb

import (
	"github.com/golang/protobuf/proto"
)

func (x *PbItem) SetPropId(val uint32) {
	x.PropId = val
}

func (x *PbItem) SetCount(val int64) {
	x.Count = val
}

func (x *PbItem) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *PbItem) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *PlayerInfo) SetUid(val uint64) {
	x.Uid = val
}

func (x *PlayerInfo) SetNickName(val string) {
	x.NickName = val
}

func (x *PlayerInfo) SetAvatar(val string) {
	x.Avatar = val
}

func (x *PlayerInfo) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *PlayerInfo) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *PlayerLoginInfo) SetLastLoginTime(val uint32) {
	x.LastLoginTime = val
}

func (x *PlayerLoginInfo) SetLastLogoutTime(val uint32) {
	x.LastLogoutTime = val
}

func (x *PlayerLoginInfo) SetNowLoginTime(val int32) {
	x.NowLoginTime = val
}

func (x *PlayerLoginInfo) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *PlayerLoginInfo) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *PlayerRoomInfo) SetGameType(val GameType) {
	x.GameType = val
}

func (x *PlayerRoomInfo) SetRoomId(val uint64) {
	x.RoomId = val
}

func (x *PlayerRoomInfo) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *PlayerRoomInfo) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *PlayerDataBase) SetPlayerInfo(val *PlayerInfo) {
	x.PlayerInfo = val
}

func (x *PlayerDataBase) SetCreateTime(val int64) {
	x.CreateTime = val
}

func (x *PlayerDataBase) SetLoginInfo(val *PlayerLoginInfo) {
	x.LoginInfo = val
}

func (x *PlayerDataBase) SetRoomInfo(val *PlayerRoomInfo) {
	x.RoomInfo = val
}

func (x *PlayerDataBase) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *PlayerDataBase) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *PlayerDataBag) SetItems(val map[uint32]*PbItem) {
	x.Items = val
}

func (x *PlayerDataBag) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *PlayerDataBag) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *PlayerData) SetId(val uint64) {
	x.Id = val
}

func (x *PlayerData) SetUid(val uint64) {
	x.Uid = val
}

func (x *PlayerData) SetVersion(val uint64) {
	x.Version = val
}

func (x *PlayerData) SetBase(val *PlayerDataBase) {
	x.Base = val
}

func (x *PlayerData) SetBag(val *PlayerDataBag) {
	x.Bag = val
}

func (x *PlayerData) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *PlayerData) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}
