// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: client_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------德州扑克房间数据-----------
type UpdateTexasRoomDataNotify struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"` // 数据类型
	Data          *TexasRoomData         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                              // 德州房间列表
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *UpdateTexasRoomDataNotify) Reset() {
	*x = UpdateTexasRoomDataNotify{}
	mi := &file_client_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTexasRoomDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTexasRoomDataNotify) ProtoMessage() {}

func (x *UpdateTexasRoomDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTexasRoomDataNotify.ProtoReflect.Descriptor instead.
func (*UpdateTexasRoomDataNotify) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateTexasRoomDataNotify) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

func (x *UpdateTexasRoomDataNotify) GetData() *TexasRoomData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteTexasRoomDataNotify struct {
	state         protoimpl.MessageState `xorm:"-"` 
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 删除房间
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *DeleteTexasRoomDataNotify) Reset() {
	*x = DeleteTexasRoomDataNotify{}
	mi := &file_client_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTexasRoomDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTexasRoomDataNotify) ProtoMessage() {}

func (x *DeleteTexasRoomDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTexasRoomDataNotify.ProtoReflect.Descriptor instead.
func (*DeleteTexasRoomDataNotify) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteTexasRoomDataNotify) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type GetTexasRoomDataReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"` // 数据类型
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetTexasRoomDataReq) Reset() {
	*x = GetTexasRoomDataReq{}
	mi := &file_client_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTexasRoomDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTexasRoomDataReq) ProtoMessage() {}

func (x *GetTexasRoomDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTexasRoomDataReq.ProtoReflect.Descriptor instead.
func (*GetTexasRoomDataReq) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{2}
}

func (x *GetTexasRoomDataReq) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

type GetTexasRoomDataRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"` // 响应头
	List          []*TexasRoomData       `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"` // 德州房间列表
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetTexasRoomDataRsp) Reset() {
	*x = GetTexasRoomDataRsp{}
	mi := &file_client_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTexasRoomDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTexasRoomDataRsp) ProtoMessage() {}

func (x *GetTexasRoomDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTexasRoomDataRsp.ProtoReflect.Descriptor instead.
func (*GetTexasRoomDataRsp) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{3}
}

func (x *GetTexasRoomDataRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetTexasRoomDataRsp) GetList() []*TexasRoomData {
	if x != nil {
		return x.List
	}
	return nil
}

// ----------Rummy房间数据-----------
type UpdateRummyRoomDataNotify struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"` // 数据类型
	List          []*RummyRoomData       `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`                                              // 德州房间列表
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *UpdateRummyRoomDataNotify) Reset() {
	*x = UpdateRummyRoomDataNotify{}
	mi := &file_client_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRummyRoomDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRummyRoomDataNotify) ProtoMessage() {}

func (x *UpdateRummyRoomDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRummyRoomDataNotify.ProtoReflect.Descriptor instead.
func (*UpdateRummyRoomDataNotify) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRummyRoomDataNotify) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

func (x *UpdateRummyRoomDataNotify) GetList() []*RummyRoomData {
	if x != nil {
		return x.List
	}
	return nil
}

type GetRummyRoomDataReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"` // 数据类型
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetRummyRoomDataReq) Reset() {
	*x = GetRummyRoomDataReq{}
	mi := &file_client_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRummyRoomDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRummyRoomDataReq) ProtoMessage() {}

func (x *GetRummyRoomDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRummyRoomDataReq.ProtoReflect.Descriptor instead.
func (*GetRummyRoomDataReq) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{5}
}

func (x *GetRummyRoomDataReq) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

type GetRummyRoomDataRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"` // 响应头
	List          []*RummyRoomData       `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"` // 德州房间列表
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetRummyRoomDataRsp) Reset() {
	*x = GetRummyRoomDataRsp{}
	mi := &file_client_db_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRummyRoomDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRummyRoomDataRsp) ProtoMessage() {}

func (x *GetRummyRoomDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRummyRoomDataRsp.ProtoReflect.Descriptor instead.
func (*GetRummyRoomDataRsp) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{6}
}

func (x *GetRummyRoomDataRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetRummyRoomDataRsp) GetList() []*RummyRoomData {
	if x != nil {
		return x.List
	}
	return nil
}

// ----------房间生成器数据------------
type UpdateGeneratorDataNotify struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"` // 数据类型
	List          []*GeneratorInfo       `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`                                              // 房间id生成器
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *UpdateGeneratorDataNotify) Reset() {
	*x = UpdateGeneratorDataNotify{}
	mi := &file_client_db_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGeneratorDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGeneratorDataNotify) ProtoMessage() {}

func (x *UpdateGeneratorDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGeneratorDataNotify.ProtoReflect.Descriptor instead.
func (*UpdateGeneratorDataNotify) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGeneratorDataNotify) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

func (x *UpdateGeneratorDataNotify) GetList() []*GeneratorInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetGeneratorDataReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"` // 数据类型
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetGeneratorDataReq) Reset() {
	*x = GetGeneratorDataReq{}
	mi := &file_client_db_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneratorDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneratorDataReq) ProtoMessage() {}

func (x *GetGeneratorDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneratorDataReq.ProtoReflect.Descriptor instead.
func (*GetGeneratorDataReq) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{8}
}

func (x *GetGeneratorDataReq) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

type GetGeneratorDataRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"` // 响应头
	List          []*GeneratorInfo       `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"` // 房间id生成器
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetGeneratorDataRsp) Reset() {
	*x = GetGeneratorDataRsp{}
	mi := &file_client_db_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneratorDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneratorDataRsp) ProtoMessage() {}

func (x *GetGeneratorDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneratorDataRsp.ProtoReflect.Descriptor instead.
func (*GetGeneratorDataRsp) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{9}
}

func (x *GetGeneratorDataRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetGeneratorDataRsp) GetList() []*GeneratorInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// ----------------玩家数据--------------
type UpdatePlayerDataNotify struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"` // 数据类型
	Data          *PlayerData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                              // 玩家数据
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *UpdatePlayerDataNotify) Reset() {
	*x = UpdatePlayerDataNotify{}
	mi := &file_client_db_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerDataNotify) ProtoMessage() {}

func (x *UpdatePlayerDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerDataNotify.ProtoReflect.Descriptor instead.
func (*UpdatePlayerDataNotify) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePlayerDataNotify) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

func (x *UpdatePlayerDataNotify) GetData() *PlayerData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateUserInfoNotify struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"`
	Data          *UserInfo              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *UpdateUserInfoNotify) Reset() {
	*x = UpdateUserInfoNotify{}
	mi := &file_client_db_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoNotify) ProtoMessage() {}

func (x *UpdateUserInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoNotify.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoNotify) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserInfoNotify) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

func (x *UpdateUserInfoNotify) GetData() *UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	UidList       []uint64               `protobuf:"varint,1,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_client_db_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserInfoReq) GetUidList() []uint64 {
	if x != nil {
		return x.UidList
	}
	return nil
}

type GetUserInfoRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	UserList      []*UserInfo            `protobuf:"bytes,2,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetUserInfoRsp) Reset() {
	*x = GetUserInfoRsp{}
	mi := &file_client_db_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRsp) ProtoMessage() {}

func (x *GetUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRsp.ProtoReflect.Descriptor instead.
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetUserInfoRsp) GetUserList() []*UserInfo {
	if x != nil {
		return x.UserList
	}
	return nil
}

// 断线重连缓存数据
type UpdateRoomInfoNotify struct {
	state         protoimpl.MessageState `xorm:"-"` 
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=poker.DataType" json:"data_type,omitempty"`
	Data          *RoomInfo              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *UpdateRoomInfoNotify) Reset() {
	*x = UpdateRoomInfoNotify{}
	mi := &file_client_db_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomInfoNotify) ProtoMessage() {}

func (x *UpdateRoomInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomInfoNotify.ProtoReflect.Descriptor instead.
func (*UpdateRoomInfoNotify) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateRoomInfoNotify) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeDataTypeNone
}

func (x *UpdateRoomInfoNotify) GetData() *RoomInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 数据查询
type GetTexasGameReportReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Round         uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetTexasGameReportReq) Reset() {
	*x = GetTexasGameReportReq{}
	mi := &file_client_db_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTexasGameReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTexasGameReportReq) ProtoMessage() {}

func (x *GetTexasGameReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTexasGameReportReq.ProtoReflect.Descriptor instead.
func (*GetTexasGameReportReq) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{15}
}

func (x *GetTexasGameReportReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GetTexasGameReportReq) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *GetTexasGameReportReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTexasGameReportReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTexasGameReportRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	List          []*TexasGameReport     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GetTexasGameReportRsp) Reset() {
	*x = GetTexasGameReportRsp{}
	mi := &file_client_db_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTexasGameReportRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTexasGameReportRsp) ProtoMessage() {}

func (x *GetTexasGameReportRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_db_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTexasGameReportRsp.ProtoReflect.Descriptor instead.
func (*GetTexasGameReportRsp) Descriptor() ([]byte, []int) {
	return file_client_db_proto_rawDescGZIP(), []int{16}
}

func (x *GetTexasGameReportRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetTexasGameReportRsp) GetList() []*TexasGameReport {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetTexasGameReportRsp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_client_db_proto protoreflect.FileDescriptor

var file_client_db_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x1a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65,
	0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78,
	0x61, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x61, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x65, 0x78, 0x61, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x43,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x61, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x63, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x61, 0x73, 0x52,
	0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x68, 0x65,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x28,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x61, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x73, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6d, 0x6d, 0x79, 0x52,
	0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x43, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x63, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x6f,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x28, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x73, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x63, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52,
	0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x28, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x6d, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x69, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x2c, 0x0a,
	0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x2b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x62, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x12, 0x2c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x69, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x77, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x61, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78,
	0x61, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x61, 0x73, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_client_db_proto_rawDescOnce sync.Once
	file_client_db_proto_rawDescData []byte
)

func file_client_db_proto_rawDescGZIP() []byte {
	file_client_db_proto_rawDescOnce.Do(func() {
		file_client_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_db_proto_rawDesc), len(file_client_db_proto_rawDesc)))
	})
	return file_client_db_proto_rawDescData
}

var file_client_db_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_client_db_proto_goTypes = []any{
	(*UpdateTexasRoomDataNotify)(nil), // 0: poker.UpdateTexasRoomDataNotify
	(*DeleteTexasRoomDataNotify)(nil), // 1: poker.DeleteTexasRoomDataNotify
	(*GetTexasRoomDataReq)(nil),       // 2: poker.GetTexasRoomDataReq
	(*GetTexasRoomDataRsp)(nil),       // 3: poker.GetTexasRoomDataRsp
	(*UpdateRummyRoomDataNotify)(nil), // 4: poker.UpdateRummyRoomDataNotify
	(*GetRummyRoomDataReq)(nil),       // 5: poker.GetRummyRoomDataReq
	(*GetRummyRoomDataRsp)(nil),       // 6: poker.GetRummyRoomDataRsp
	(*UpdateGeneratorDataNotify)(nil), // 7: poker.UpdateGeneratorDataNotify
	(*GetGeneratorDataReq)(nil),       // 8: poker.GetGeneratorDataReq
	(*GetGeneratorDataRsp)(nil),       // 9: poker.GetGeneratorDataRsp
	(*UpdatePlayerDataNotify)(nil),    // 10: poker.UpdatePlayerDataNotify
	(*UpdateUserInfoNotify)(nil),      // 11: poker.UpdateUserInfoNotify
	(*GetUserInfoReq)(nil),            // 12: poker.GetUserInfoReq
	(*GetUserInfoRsp)(nil),            // 13: poker.GetUserInfoRsp
	(*UpdateRoomInfoNotify)(nil),      // 14: poker.UpdateRoomInfoNotify
	(*GetTexasGameReportReq)(nil),     // 15: poker.GetTexasGameReportReq
	(*GetTexasGameReportRsp)(nil),     // 16: poker.GetTexasGameReportRsp
	(DataType)(0),                     // 17: poker.DataType
	(*TexasRoomData)(nil),             // 18: poker.TexasRoomData
	(*RspHead)(nil),                   // 19: poker.RspHead
	(*RummyRoomData)(nil),             // 20: poker.RummyRoomData
	(*GeneratorInfo)(nil),             // 21: poker.GeneratorInfo
	(*PlayerData)(nil),                // 22: poker.PlayerData
	(*UserInfo)(nil),                  // 23: poker.UserInfo
	(*RoomInfo)(nil),                  // 24: poker.RoomInfo
	(*TexasGameReport)(nil),           // 25: poker.TexasGameReport
}
var file_client_db_proto_depIdxs = []int32{
	17, // 0: poker.UpdateTexasRoomDataNotify.data_type:type_name -> poker.DataType
	18, // 1: poker.UpdateTexasRoomDataNotify.data:type_name -> poker.TexasRoomData
	17, // 2: poker.GetTexasRoomDataReq.data_type:type_name -> poker.DataType
	19, // 3: poker.GetTexasRoomDataRsp.head:type_name -> poker.RspHead
	18, // 4: poker.GetTexasRoomDataRsp.list:type_name -> poker.TexasRoomData
	17, // 5: poker.UpdateRummyRoomDataNotify.data_type:type_name -> poker.DataType
	20, // 6: poker.UpdateRummyRoomDataNotify.list:type_name -> poker.RummyRoomData
	17, // 7: poker.GetRummyRoomDataReq.data_type:type_name -> poker.DataType
	19, // 8: poker.GetRummyRoomDataRsp.head:type_name -> poker.RspHead
	20, // 9: poker.GetRummyRoomDataRsp.list:type_name -> poker.RummyRoomData
	17, // 10: poker.UpdateGeneratorDataNotify.data_type:type_name -> poker.DataType
	21, // 11: poker.UpdateGeneratorDataNotify.list:type_name -> poker.GeneratorInfo
	17, // 12: poker.GetGeneratorDataReq.data_type:type_name -> poker.DataType
	19, // 13: poker.GetGeneratorDataRsp.head:type_name -> poker.RspHead
	21, // 14: poker.GetGeneratorDataRsp.list:type_name -> poker.GeneratorInfo
	17, // 15: poker.UpdatePlayerDataNotify.data_type:type_name -> poker.DataType
	22, // 16: poker.UpdatePlayerDataNotify.data:type_name -> poker.PlayerData
	17, // 17: poker.UpdateUserInfoNotify.data_type:type_name -> poker.DataType
	23, // 18: poker.UpdateUserInfoNotify.data:type_name -> poker.UserInfo
	19, // 19: poker.GetUserInfoRsp.head:type_name -> poker.RspHead
	23, // 20: poker.GetUserInfoRsp.user_list:type_name -> poker.UserInfo
	17, // 21: poker.UpdateRoomInfoNotify.data_type:type_name -> poker.DataType
	24, // 22: poker.UpdateRoomInfoNotify.data:type_name -> poker.RoomInfo
	19, // 23: poker.GetTexasGameReportRsp.head:type_name -> poker.RspHead
	25, // 24: poker.GetTexasGameReportRsp.list:type_name -> poker.TexasGameReport
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_client_db_proto_init() }
func file_client_db_proto_init() {
	if File_client_db_proto != nil {
		return
	}
	file_packet_proto_init()
	file_global_enum_proto_init()
	file_database_proto_init()
	file_report_proto_init()
	file_player_data_proto_init()
	file_client_room_rummy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_db_proto_rawDesc), len(file_client_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_db_proto_goTypes,
		DependencyIndexes: file_client_db_proto_depIdxs,
		MessageInfos:      file_client_db_proto_msgTypes,
	}.Build()
	File_client_db_proto = out.File
	file_client_db_proto_goTypes = nil
	file_client_db_proto_depIdxs = nil
}
