// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: client_match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TexasQueryReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *TexasQueryReq) Reset() {
	*x = TexasQueryReq{}
	mi := &file_client_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasQueryReq) ProtoMessage() {}

func (x *TexasQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasQueryReq.ProtoReflect.Descriptor instead.
func (*TexasQueryReq) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{0}
}

func (x *TexasQueryReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type TexasQueryRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Data          *TexasRoomData         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *TexasQueryRsp) Reset() {
	*x = TexasQueryRsp{}
	mi := &file_client_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasQueryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasQueryRsp) ProtoMessage() {}

func (x *TexasQueryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasQueryRsp.ProtoReflect.Descriptor instead.
func (*TexasQueryRsp) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{1}
}

func (x *TexasQueryRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *TexasQueryRsp) GetData() *TexasRoomData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 匹配房间请求
type TexasMatchRoomReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	TableId       uint32                 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	RoomId        uint64                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *TexasMatchRoomReq) Reset() {
	*x = TexasMatchRoomReq{}
	mi := &file_client_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasMatchRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasMatchRoomReq) ProtoMessage() {}

func (x *TexasMatchRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasMatchRoomReq.ProtoReflect.Descriptor instead.
func (*TexasMatchRoomReq) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{2}
}

func (x *TexasMatchRoomReq) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *TexasMatchRoomReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type TexasMatchRoomRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	TableId       uint32                 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	RoomId        uint64                 `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *TexasMatchRoomRsp) Reset() {
	*x = TexasMatchRoomRsp{}
	mi := &file_client_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasMatchRoomRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasMatchRoomRsp) ProtoMessage() {}

func (x *TexasMatchRoomRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasMatchRoomRsp.ProtoReflect.Descriptor instead.
func (*TexasMatchRoomRsp) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{3}
}

func (x *TexasMatchRoomRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *TexasMatchRoomRsp) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *TexasMatchRoomRsp) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 获取房间列表请求
type TexasRoomListReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	GameType      int32                  `protobuf:"varint,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"` // 游戏类型
	CoinType      int32                  `protobuf:"varint,2,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"` // 币种类型
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *TexasRoomListReq) Reset() {
	*x = TexasRoomListReq{}
	mi := &file_client_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasRoomListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasRoomListReq) ProtoMessage() {}

func (x *TexasRoomListReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasRoomListReq.ProtoReflect.Descriptor instead.
func (*TexasRoomListReq) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{4}
}

func (x *TexasRoomListReq) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

func (x *TexasRoomListReq) GetCoinType() int32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

type TexasRoomListRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	RoomList      []*TexasRoomInfo       `protobuf:"bytes,2,rep,name=room_list,json=roomList,proto3" json:"room_list,omitempty"` // 房间列表
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *TexasRoomListRsp) Reset() {
	*x = TexasRoomListRsp{}
	mi := &file_client_match_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasRoomListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasRoomListRsp) ProtoMessage() {}

func (x *TexasRoomListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasRoomListRsp.ProtoReflect.Descriptor instead.
func (*TexasRoomListRsp) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{5}
}

func (x *TexasRoomListRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *TexasRoomListRsp) GetRoomList() []*TexasRoomInfo {
	if x != nil {
		return x.RoomList
	}
	return nil
}

type RummyRoomListReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	GameType      int32                  `protobuf:"varint,1,opt,name=GameType,proto3" json:"GameType,omitempty"` // 游戏类型
	CoinType      int32                  `protobuf:"varint,2,opt,name=CoinType,proto3" json:"CoinType,omitempty"` // 币种类型
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *RummyRoomListReq) Reset() {
	*x = RummyRoomListReq{}
	mi := &file_client_match_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RummyRoomListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RummyRoomListReq) ProtoMessage() {}

func (x *RummyRoomListReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RummyRoomListReq.ProtoReflect.Descriptor instead.
func (*RummyRoomListReq) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{6}
}

func (x *RummyRoomListReq) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

func (x *RummyRoomListReq) GetCoinType() int32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

type RummyRoomListRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	RoomList      []*RummyRoomPubData    `protobuf:"bytes,2,rep,name=room_list,json=roomList,proto3" json:"room_list,omitempty"` // 房间列表
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *RummyRoomListRsp) Reset() {
	*x = RummyRoomListRsp{}
	mi := &file_client_match_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RummyRoomListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RummyRoomListRsp) ProtoMessage() {}

func (x *RummyRoomListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RummyRoomListRsp.ProtoReflect.Descriptor instead.
func (*RummyRoomListRsp) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{7}
}

func (x *RummyRoomListRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *RummyRoomListRsp) GetRoomList() []*RummyRoomPubData {
	if x != nil {
		return x.RoomList
	}
	return nil
}

type HasRoomReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *HasRoomReq) Reset() {
	*x = HasRoomReq{}
	mi := &file_client_match_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasRoomReq) ProtoMessage() {}

func (x *HasRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasRoomReq.ProtoReflect.Descriptor instead.
func (*HasRoomReq) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{8}
}

func (x *HasRoomReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type HasRoomRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	IsExist       bool                   `protobuf:"varint,2,opt,name=is_exist,json=isExist,proto3" json:"is_exist,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *HasRoomRsp) Reset() {
	*x = HasRoomRsp{}
	mi := &file_client_match_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasRoomRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasRoomRsp) ProtoMessage() {}

func (x *HasRoomRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasRoomRsp.ProtoReflect.Descriptor instead.
func (*HasRoomRsp) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{9}
}

func (x *HasRoomRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *HasRoomRsp) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

// 加入比赛请求
type SngJoinRoomReq struct {
	state         protoimpl.MessageState `xorm:"-"` 
	MatchId       int32                  `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // match配置id
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *SngJoinRoomReq) Reset() {
	*x = SngJoinRoomReq{}
	mi := &file_client_match_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SngJoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SngJoinRoomReq) ProtoMessage() {}

func (x *SngJoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SngJoinRoomReq.ProtoReflect.Descriptor instead.
func (*SngJoinRoomReq) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{10}
}

func (x *SngJoinRoomReq) GetMatchId() int32 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

type SngJoinRoomRsp struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Head          *RspHead               `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	RoomId        uint64                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	Chip          int64                  `protobuf:"varint,3,opt,name=chip,proto3" json:"chip,omitempty"`                   // 玩家初始筹码
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *SngJoinRoomRsp) Reset() {
	*x = SngJoinRoomRsp{}
	mi := &file_client_match_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SngJoinRoomRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SngJoinRoomRsp) ProtoMessage() {}

func (x *SngJoinRoomRsp) ProtoReflect() protoreflect.Message {
	mi := &file_client_match_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SngJoinRoomRsp.ProtoReflect.Descriptor instead.
func (*SngJoinRoomRsp) Descriptor() ([]byte, []int) {
	return file_client_match_proto_rawDescGZIP(), []int{11}
}

func (x *SngJoinRoomRsp) GetHead() *RspHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *SngJoinRoomRsp) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SngJoinRoomRsp) GetChip() int64 {
	if x != nil {
		return x.Chip
	}
	return 0
}

var File_client_match_proto protoreflect.FileDescriptor

var file_client_match_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x1a, 0x0c, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x75, 0x6d, 0x6d, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0d, 0x54, 0x65, 0x78, 0x61, 0x73, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0x5d, 0x0a, 0x0d, 0x54, 0x65, 0x78, 0x61, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x73, 0x70,
	0x12, 0x22, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x61, 0x73,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x47,
	0x0a, 0x11, 0x54, 0x65, 0x78, 0x61, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x11, 0x54, 0x65, 0x78, 0x61, 0x73,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x61, 0x73, 0x52, 0x6f, 0x6f,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x69, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x61, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x73, 0x70,
	0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x31, 0x0a, 0x09, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x61, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4a, 0x0a,
	0x10, 0x52, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x43, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6c, 0x0a, 0x10, 0x52, 0x75, 0x6d,
	0x6d, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x12, 0x34, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6d,
	0x6d, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x75, 0x62, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x72,
	0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0a, 0x48, 0x61, 0x73, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x4b,
	0x0a, 0x0a, 0x48, 0x61, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x72, 0x2e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x0e, 0x53,
	0x6e, 0x67, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x0e, 0x53, 0x6e, 0x67, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x68, 0x65,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x68, 0x69, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x68, 0x69, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_client_match_proto_rawDescOnce sync.Once
	file_client_match_proto_rawDescData []byte
)

func file_client_match_proto_rawDescGZIP() []byte {
	file_client_match_proto_rawDescOnce.Do(func() {
		file_client_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_match_proto_rawDesc), len(file_client_match_proto_rawDesc)))
	})
	return file_client_match_proto_rawDescData
}

var file_client_match_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_client_match_proto_goTypes = []any{
	(*TexasQueryReq)(nil),     // 0: poker.TexasQueryReq
	(*TexasQueryRsp)(nil),     // 1: poker.TexasQueryRsp
	(*TexasMatchRoomReq)(nil), // 2: poker.TexasMatchRoomReq
	(*TexasMatchRoomRsp)(nil), // 3: poker.TexasMatchRoomRsp
	(*TexasRoomListReq)(nil),  // 4: poker.TexasRoomListReq
	(*TexasRoomListRsp)(nil),  // 5: poker.TexasRoomListRsp
	(*RummyRoomListReq)(nil),  // 6: poker.RummyRoomListReq
	(*RummyRoomListRsp)(nil),  // 7: poker.RummyRoomListRsp
	(*HasRoomReq)(nil),        // 8: poker.HasRoomReq
	(*HasRoomRsp)(nil),        // 9: poker.HasRoomRsp
	(*SngJoinRoomReq)(nil),    // 10: poker.SngJoinRoomReq
	(*SngJoinRoomRsp)(nil),    // 11: poker.SngJoinRoomRsp
	(*RspHead)(nil),           // 12: poker.RspHead
	(*TexasRoomData)(nil),     // 13: poker.TexasRoomData
	(*TexasRoomInfo)(nil),     // 14: poker.TexasRoomInfo
	(*RummyRoomPubData)(nil),  // 15: poker.RummyRoomPubData
}
var file_client_match_proto_depIdxs = []int32{
	12, // 0: poker.TexasQueryRsp.head:type_name -> poker.RspHead
	13, // 1: poker.TexasQueryRsp.data:type_name -> poker.TexasRoomData
	12, // 2: poker.TexasMatchRoomRsp.head:type_name -> poker.RspHead
	12, // 3: poker.TexasRoomListRsp.head:type_name -> poker.RspHead
	14, // 4: poker.TexasRoomListRsp.room_list:type_name -> poker.TexasRoomInfo
	12, // 5: poker.RummyRoomListRsp.head:type_name -> poker.RspHead
	15, // 6: poker.RummyRoomListRsp.room_list:type_name -> poker.RummyRoomPubData
	12, // 7: poker.HasRoomRsp.head:type_name -> poker.RspHead
	12, // 8: poker.SngJoinRoomRsp.head:type_name -> poker.RspHead
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_client_match_proto_init() }
func file_client_match_proto_init() {
	if File_client_match_proto != nil {
		return
	}
	file_packet_proto_init()
	file_database_proto_init()
	file_client_room_proto_init()
	file_client_room_rummy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_match_proto_rawDesc), len(file_client_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_match_proto_goTypes,
		DependencyIndexes: file_client_match_proto_depIdxs,
		MessageInfos:      file_client_match_proto_msgTypes,
	}.Build()
	File_client_match_proto = out.File
	file_client_match_proto_goTypes = nil
	file_client_match_proto_depIdxs = nil
}
