// Code generated by protoc-gen-go-xorm. DO NOT EDIT.
// Source: client_builder.proto

package pb

import (
	"github.com/golang/protobuf/proto"
)

func (x *GenRoomIdReq) SetGeneratorType(val GeneratorType) {
	x.GeneratorType = val
}

func (x *GenRoomIdReq) SetMatchType(val MatchType) {
	x.MatchType = val
}

func (x *GenRoomIdReq) SetGameType(val GameType) {
	x.GameType = val
}

func (x *GenRoomIdReq) SetCoinType(val CoinType) {
	x.CoinType = val
}

func (x *GenRoomIdReq) SetCount(val int32) {
	x.Count = val
}

func (x *GenRoomIdReq) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GenRoomIdReq) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GenRoomIdRsp) SetHead(val *RspHead) {
	x.Head = val
}

func (x *GenRoomIdRsp) SetRoomIdList(val []uint64) {
	x.RoomIdList = val
}

func (x *GenRoomIdRsp) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GenRoomIdRsp) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *DefaultRoomId) SetMatchType(val MatchType) {
	x.MatchType = val
}

func (x *DefaultRoomId) SetGameType(val GameType) {
	x.GameType = val
}

func (x *DefaultRoomId) SetCoinType(val CoinType) {
	x.CoinType = val
}

func (x *DefaultRoomId) SetIncr(val uint32) {
	x.Incr = val
}

func (x *DefaultRoomId) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *DefaultRoomId) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}
