// Code generated by protoc-gen-go-xorm. DO NOT EDIT.
// Source: client_db.proto

package pb

import (
	"github.com/golang/protobuf/proto"
)

func (x *UpdateTexasRoomDataNotify) SetDataType(val DataType) {
	x.DataType = val
}

func (x *UpdateTexasRoomDataNotify) SetData(val *TexasRoomData) {
	x.Data = val
}

func (x *UpdateTexasRoomDataNotify) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *UpdateTexasRoomDataNotify) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *DeleteTexasRoomDataNotify) SetRoomId(val uint64) {
	x.RoomId = val
}

func (x *DeleteTexasRoomDataNotify) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *DeleteTexasRoomDataNotify) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetTexasRoomDataReq) SetDataType(val DataType) {
	x.DataType = val
}

func (x *GetTexasRoomDataReq) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetTexasRoomDataReq) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetTexasRoomDataRsp) SetHead(val *RspHead) {
	x.Head = val
}

func (x *GetTexasRoomDataRsp) SetList(val []*TexasRoomData) {
	x.List = val
}

func (x *GetTexasRoomDataRsp) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetTexasRoomDataRsp) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *UpdateRummyRoomDataNotify) SetDataType(val DataType) {
	x.DataType = val
}

func (x *UpdateRummyRoomDataNotify) SetList(val []*RummyRoomData) {
	x.List = val
}

func (x *UpdateRummyRoomDataNotify) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *UpdateRummyRoomDataNotify) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetRummyRoomDataReq) SetDataType(val DataType) {
	x.DataType = val
}

func (x *GetRummyRoomDataReq) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetRummyRoomDataReq) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetRummyRoomDataRsp) SetHead(val *RspHead) {
	x.Head = val
}

func (x *GetRummyRoomDataRsp) SetList(val []*RummyRoomData) {
	x.List = val
}

func (x *GetRummyRoomDataRsp) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetRummyRoomDataRsp) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *UpdateGeneratorDataNotify) SetDataType(val DataType) {
	x.DataType = val
}

func (x *UpdateGeneratorDataNotify) SetList(val []*GeneratorInfo) {
	x.List = val
}

func (x *UpdateGeneratorDataNotify) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *UpdateGeneratorDataNotify) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetGeneratorDataReq) SetDataType(val DataType) {
	x.DataType = val
}

func (x *GetGeneratorDataReq) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetGeneratorDataReq) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetGeneratorDataRsp) SetHead(val *RspHead) {
	x.Head = val
}

func (x *GetGeneratorDataRsp) SetList(val []*GeneratorInfo) {
	x.List = val
}

func (x *GetGeneratorDataRsp) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetGeneratorDataRsp) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *UpdatePlayerDataNotify) SetDataType(val DataType) {
	x.DataType = val
}

func (x *UpdatePlayerDataNotify) SetData(val *PlayerData) {
	x.Data = val
}

func (x *UpdatePlayerDataNotify) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *UpdatePlayerDataNotify) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *UpdateUserInfoNotify) SetDataType(val DataType) {
	x.DataType = val
}

func (x *UpdateUserInfoNotify) SetData(val *UserInfo) {
	x.Data = val
}

func (x *UpdateUserInfoNotify) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *UpdateUserInfoNotify) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetUserInfoReq) SetUidList(val []uint64) {
	x.UidList = val
}

func (x *GetUserInfoReq) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetUserInfoReq) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetUserInfoRsp) SetHead(val *RspHead) {
	x.Head = val
}

func (x *GetUserInfoRsp) SetUserList(val []*UserInfo) {
	x.UserList = val
}

func (x *GetUserInfoRsp) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetUserInfoRsp) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *UpdateRoomInfoNotify) SetDataType(val DataType) {
	x.DataType = val
}

func (x *UpdateRoomInfoNotify) SetData(val *RoomInfo) {
	x.Data = val
}

func (x *UpdateRoomInfoNotify) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *UpdateRoomInfoNotify) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetTexasGameReportReq) SetRoomId(val uint64) {
	x.RoomId = val
}

func (x *GetTexasGameReportReq) SetRound(val uint32) {
	x.Round = val
}

func (x *GetTexasGameReportReq) SetPage(val uint32) {
	x.Page = val
}

func (x *GetTexasGameReportReq) SetPageSize(val uint32) {
	x.PageSize = val
}

func (x *GetTexasGameReportReq) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetTexasGameReportReq) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GetTexasGameReportRsp) SetHead(val *RspHead) {
	x.Head = val
}

func (x *GetTexasGameReportRsp) SetList(val []*TexasGameReport) {
	x.List = val
}

func (x *GetTexasGameReportRsp) SetTotalCount(val int64) {
	x.TotalCount = val
}

func (x *GetTexasGameReportRsp) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GetTexasGameReportRsp) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}
