// Code generated by protoc-gen-go-xorm. DO NOT EDIT.
// Source: database.proto

package pb

import (
	"github.com/golang/protobuf/proto"
)

func (x *GeneratorInfo) SetId(val GeneratorType) {
	x.Id = val
}

func (x *GeneratorInfo) SetIncr(val uint32) {
	x.Incr = val
}

func (x *GeneratorInfo) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GeneratorInfo) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *GeneratorData) SetList(val []*GeneratorInfo) {
	x.List = val
}

func (x *GeneratorData) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *GeneratorData) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *UserInfo) SetUid(val uint64) {
	x.Uid = val
}

func (x *UserInfo) SetName(val string) {
	x.Name = val
}

func (x *UserInfo) SetAvatar(val string) {
	x.Avatar = val
}

func (x *UserInfo) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *UserInfo) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *RoomInfo) SetUid(val uint64) {
	x.Uid = val
}

func (x *RoomInfo) SetGameType(val GameType) {
	x.GameType = val
}

func (x *RoomInfo) SetRoomId(val uint64) {
	x.RoomId = val
}

func (x *RoomInfo) SetTableId(val uint32) {
	x.TableId = val
}

func (x *RoomInfo) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *RoomInfo) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *TexasRoomData) SetRoomId(val uint64) {
	x.RoomId = val
}

func (x *TexasRoomData) SetGameId(val int32) {
	x.GameId = val
}

func (x *TexasRoomData) SetRoomState(val RoomStatus) {
	x.RoomState = val
}

func (x *TexasRoomData) SetCreateTime(val int64) {
	x.CreateTime = val
}

func (x *TexasRoomData) SetTable(val *TexasTableData) {
	x.Table = val
}

func (x *TexasRoomData) SetTotalBuyinChips(val int64) {
	x.TotalBuyinChips = val
}

func (x *TexasRoomData) SetTotalServiceChips(val int64) {
	x.TotalServiceChips = val
}

func (x *TexasRoomData) SetTotalRuningWater(val int64) {
	x.TotalRuningWater = val
}

func (x *TexasRoomData) SetOnlineNumber(val int64) {
	x.OnlineNumber = val
}

func (x *TexasRoomData) SetFinishFlag(val uint32) {
	x.FinishFlag = val
}

func (x *TexasRoomData) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *TexasRoomData) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *TexasTableData) SetCurState(val GameState) {
	x.CurState = val
}

func (x *TexasTableData) SetRound(val uint32) {
	x.Round = val
}

func (x *TexasTableData) SetPlayers(val map[uint64]*TexasPlayerData) {
	x.Players = val
}

func (x *TexasTableData) SetChairInfo(val map[uint32]uint64) {
	x.ChairInfo = val
}

func (x *TexasTableData) SetGameData(val *TexasGameData) {
	x.GameData = val
}

func (x *TexasTableData) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *TexasTableData) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *TexasPlayerData) SetUid(val uint64) {
	x.Uid = val
}

func (x *TexasPlayerData) SetChips(val int64) {
	x.Chips = val
}

func (x *TexasPlayerData) SetChairId(val uint32) {
	x.ChairId = val
}

func (x *TexasPlayerData) SetPlayerState(val PlayerStatus) {
	x.PlayerState = val
}

func (x *TexasPlayerData) SetGameInfo(val *TexasPlayerGameInfo) {
	x.GameInfo = val
}

func (x *TexasPlayerData) SetTotalIncr(val int64) {
	x.TotalIncr = val
}

func (x *TexasPlayerData) SetTotalBuyin(val int64) {
	x.TotalBuyin = val
}

func (x *TexasPlayerData) SetTotalTimes(val uint32) {
	x.TotalTimes = val
}

func (x *TexasPlayerData) SetSngChairId(val uint32) {
	x.SngChairId = val
}

func (x *TexasPlayerData) SetRank(val uint32) {
	x.Rank = val
}

func (x *TexasPlayerData) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *TexasPlayerData) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *TexasPlayerGameInfo) SetPosition(val uint32) {
	x.Position = val
}

func (x *TexasPlayerGameInfo) SetGameState(val GameState) {
	x.GameState = val
}

func (x *TexasPlayerGameInfo) SetOperate(val OperateType) {
	x.Operate = val
}

func (x *TexasPlayerGameInfo) SetBetChips(val int64) {
	x.BetChips = val
}

func (x *TexasPlayerGameInfo) SetPreOperate(val OperateType) {
	x.PreOperate = val
}

func (x *TexasPlayerGameInfo) SetPreBetChips(val int64) {
	x.PreBetChips = val
}

func (x *TexasPlayerGameInfo) SetBestCardType(val CardType) {
	x.BestCardType = val
}

func (x *TexasPlayerGameInfo) SetBestCardValue(val uint32) {
	x.BestCardValue = val
}

func (x *TexasPlayerGameInfo) SetBestCardList(val []uint32) {
	x.BestCardList = val
}

func (x *TexasPlayerGameInfo) SetHandCardList(val []uint32) {
	x.HandCardList = val
}

func (x *TexasPlayerGameInfo) SetHand_ShowList(val []bool) {
	x.Hand_ShowList = val
}

func (x *TexasPlayerGameInfo) SetTotalBetChips(val int64) {
	x.TotalBetChips = val
}

func (x *TexasPlayerGameInfo) SetIsChange(val bool) {
	x.IsChange = val
}

func (x *TexasPlayerGameInfo) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *TexasPlayerGameInfo) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *TexasGameData) SetDealerChairId(val uint32) {
	x.DealerChairId = val
}

func (x *TexasGameData) SetSmallChairId(val uint32) {
	x.SmallChairId = val
}

func (x *TexasGameData) SetBigChairId(val uint32) {
	x.BigChairId = val
}

func (x *TexasGameData) SetMinRaise(val int64) {
	x.MinRaise = val
}

func (x *TexasGameData) SetMaxBetChips(val int64) {
	x.MaxBetChips = val
}

func (x *TexasGameData) SetPublicCardList(val []uint32) {
	x.PublicCardList = val
}

func (x *TexasGameData) SetUidCursor(val uint32) {
	x.UidCursor = val
}

func (x *TexasGameData) SetUidList(val []uint64) {
	x.UidList = val
}

func (x *TexasGameData) SetPotPool(val *TexasPotPoolData) {
	x.PotPool = val
}

func (x *TexasGameData) SetIsCompare(val bool) {
	x.IsCompare = val
}

func (x *TexasGameData) SetCardCursor(val uint32) {
	x.CardCursor = val
}

func (x *TexasGameData) SetCardList(val []uint32) {
	x.CardList = val
}

func (x *TexasGameData) SetRankUidList(val []uint64) {
	x.RankUidList = val
}

func (x *TexasGameData) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *TexasGameData) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *TexasPotPoolData) SetTotalBetChips(val int64) {
	x.TotalBetChips = val
}

func (x *TexasPotPoolData) SetBetChips(val int64) {
	x.BetChips = val
}

func (x *TexasPotPoolData) SetPotList(val []*TexasPotData) {
	x.PotList = val
}

func (x *TexasPotPoolData) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *TexasPotPoolData) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}

func (x *TexasPotData) SetPotType(val uint32) {
	x.PotType = val
}

func (x *TexasPotData) SetChips(val int64) {
	x.Chips = val
}

func (x *TexasPotData) SetUidList(val []uint64) {
	x.UidList = val
}

func (x *TexasPotData) FromDB(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	return proto.Unmarshal(data, x)
}

func (x *TexasPotData) ToDB() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	return proto.Marshal(x)
}
