mysql:
  1:
    dbname: poker
    user: root
    password: 123456
    host: 127.0.0.1:13306
    slave:

redis:
  1:
    dbname: poker
    db: 1
    user: default
    password: 123456
    host: 127.0.0.1:16379
  
mongodb:
  1:
    dbname: poker
    user: root
    password: 123456
    host: 127.0.0.1:17017
    slave: 
      1: 
        dbname:  poker
        user: root
        password: 123456
        host: 127.0.0.1:17017

etcd:
  topic: poker_server/etcd
  endpoints:
    - http://127.0.0.1:12379
  
nats:
  topic: poker_server/nats
  endpoints: 127.0.0.1:14222

common:
  env: develop  # develop, beta, release 
  config_is_remote: true
  config_path: /data/poker/data
  config_topic: poker/config
  router_expire: 900
  discovery_expire: 20
  secret_key: gH7%kL9!qW2#sD4*FpV6&nZ8@xJ0^yT1

php:
  user_info_url: http://172.32.75.53:8010/mg/callback/ACE/getUserInfo

client:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/client.log
    ip: 127.0.0.1
    port: 10101
    http_port: 22345

gate:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/gate1.log
    ip: 3.108.218.6
    port: 10101
    http_port: 10001

room:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/room1.log
    ip: 127.0.0.1
    port: 10201

match:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/match1.log
    ip: 127.0.0.1
    port: 10301


db:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/db1.log
    ip: 127.0.0.1
    port: 10401

builder:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/builder1.log
    ip: 127.0.0.1
    port: 10501
  
game:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/game1.log
    ip: 127.0.0.1
    port: 10601

gm:
  1:
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/gm1.log
    ip: 127.0.0.1
    port: 10701
