mysql:
  1:
    dbname: universal
    user: root
    password: 123456
    host: localhost:3306
    slave:

redis:
  1:
    dbname: universal
    db: 1
    user: default
    password: 123456
    host: localhost:6379
  
mongodb:
  1:
    dbname: universal
    user: root
    password: 123456
    host: localhost:27017
    slave: #从设备
      1: localhost:27017
      2: localhost:27017
    
etcd:
  channel: universal/etcd
  endpoints:
    - http://localhost:2379

nats:
  channel: universal/nats
  endpoints: localhost:4222

configure:
  local_path: ./data

cluster:
  gate:
    env: develop  # develop, beta, release 
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/gate.log
    router_expire: 900
    discovery_expire: 20
    http: 
      screte_key: gH7%kL9!qW2#sD4*FpV6&nZ8@xJ0^yT1
      host: localhost:10001
    nodes:
      1: 
        host: localhost:10101
        pprof: localhost:11101
  room:
    env: develop  # develop, beta, release 
    log_level: warn # info, debug, warn, error, fatal
    log_file: ./log/room.log
    router_expire: 900
    discovery_expire: 20
    nodes:
      1: 
        host: localhost:10201
        pprof: localhost:11201
  match:
    env: develop  # develop, beta, release 
    log_level: debug # info, debug, warn, error, fatal
    log_file: ./log/match.log
    router_expire: 900
    discovery_expire: 20
    nodes:
      1: 
        host: localhost:10301
        pprof: localhost:11301


