mysql:
  1:
    dbname: poker
    user: root
    password: 123456
    host: 13.203.103.190:13306
    slave:

redis:
  1:
    dbname: poker
    db: 1
    user: default
    password: 123456
    host: 13.203.103.190:16379
  
mongodb:
  1:
    dbname: poker
    user: root
    password: 123456
    host: 13.203.103.190:17017
    slave: 
      1: 
        dbname: poker
        user: root
        password: 123456
        host: 13.203.103.190:17017

etcd:
  topic: poker_server/etcd
  endpoints:
    - http://13.203.103.190:12379
  
nats:
  topic: poker_server/nats
  endpoints: 13.203.103.190:14222

data:
  is_remote: true
  path: ./data
  topic: poker/config
  endpoints:
    - http://13.203.103.190:12379

common:
  env: release  # develop, beta, release 
  secret_key: gH7%kL9!qW2#sD4*FpV6&nZ8@xJ0^yT1

client:
  1:
    router_ttl: 900
    discovery_ttl: 20
    log_level: debug # info, debug, warn, error, fatal
    log_path: ./log
    ip: 13.203.103.190
    port: 10101
    http_port: 22345

gate:
  1:
    router_ttl: 900
    discovery_ttl: 20
    log_level: debug # info, debug, warn, error, fatal
    log_path: ./log
    ip: 13.203.103.190
    port: 10101
    http_port: 10001

room:
  1:
    router_ttl: 900
    discovery_ttl: 20
    log_level: debug # info, debug, warn, error, fatal
    log_path: ./log
    ip: 13.203.103.190
    port: 10201

match:
  1:
    router_ttl: 900
    discovery_ttl: 20
    log_level: debug # info, debug, warn, error, fatal
    log_path: ./log
    ip: 13.203.103.190
    port: 10301

db:
  1:
    router_ttl: 900000
    discovery_ttl: 20
    log_level: debug # info, debug, warn, error, fatal
    log_path: ./log
    ip: localhost
    port: 10401

builder:
  1:
    router_ttl: 900000
    discovery_ttl: 20
    log_level: debug # info, debug, warn, error, fatal
    log_path: ./log
    ip: localhost
    port: 10501

game:
  1:
    router_ttl: 900
    discovery_ttl: 20
    log_level: debug # info, debug, warn, error, fatal
    log_path: ./log
    ip: localhost
    port: 10601

gm:
  1:
    router_ttl: 900
    discovery_ttl: 20
    log_level: debug # info, debug, warn, error, fatal
    log_path: ./log
    ip: localhost
    port: 10701
