// Code generated by dbtool, DO NOT EDIT.

package {{.Package}}

func init() {
	routeTable = make(map[routeKeyType]DBHandleFunc)
	{{range $v := .Sets}} registerFunc({{$v.GetName}}, handle{{$v.GetHanldeFuncName}})
	{{end}}
}
